# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rms.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import matplotlib.pyplot as plt
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from PyQt5.QtWidgets import QApplication, QWidget
import numpy as np
import receiver

class Ui_5Peaks(QWidget):
    def setupUi(self, Graph5Peaks):
        Graph5Peaks.setObjectName("Graph5Peaks")
        Graph5Peaks.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(Graph5Peaks)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(90, 60, 619, 519))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 5, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 3, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 5, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 4, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 4, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(220, 20, 331, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        Graph5Peaks.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Graph5Peaks)
        self.statusbar.setObjectName("statusbar")
        Graph5Peaks.setStatusBar(self.statusbar)

        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("Volver")
        self.gridLayout.addWidget(self.pushButton, 6,0,1,1)
        self.pushButton.setText("Volver")

        self.pushButton.clicked.connect(self.volverMenu)
        self.pushButton.clicked.connect(Graph5Peaks.close)

        self.retranslateUi(Graph5Peaks)
        QtCore.QMetaObject.connectSlotsByName(Graph5Peaks)

        #tomamos los datos
        peak_ax = receiver.peak_ax
        peak_ay = receiver.peak_ay
        peak_az = receiver.peak_az
        peak_gx = receiver.peak_gx
        peak_gy = receiver.peak_gy
        peak_gz = receiver.peak_gz
        #agregamos los peaks
        self.label_2.setText(peak_ax)
        self.label_4.setText(peak_ay)
        self.label_6.setText(peak_az)

        self.label_8.setText(peak_gx)
        self.label_10.setText(peak_gy)
        self.label_12.setText(peak_gz)

        self.label_2.adjustSize()
        self.label_4.adjustSize()
        self.label_6.adjustSize()
        self.label_8.adjustSize()
        self.label_10.adjustSize()
        self.label_12.adjustSize()
    
    def volverMenu(self):
        from main_app import Ui_MainWindow
        self.window2 = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.window2)
        self.window2.show()

    def retranslateUi(self, Graph5Peaks):
        _translate = QtCore.QCoreApplication.translate
        Graph5Peaks.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_6.setText(_translate("MainWindow", "az"))
        self.label_12.setText(_translate("MainWindow", "gz"))
        self.label_8.setText(_translate("MainWindow", "gx"))
        self.label_11.setText(_translate("MainWindow", "Giroscopio en Z:"))
        self.label_3.setText(_translate("MainWindow", "Aceleración en Y:"))
        self.label_5.setText(_translate("MainWindow", "Aceleración en Z:"))
        self.label_4.setText(_translate("MainWindow", "ay"))
        self.label_7.setText(_translate("MainWindow", "Giroscopio en X:"))
        self.label_2.setText(_translate("MainWindow", "ax"))
        self.label_9.setText(_translate("MainWindow", "Giroscopio en Y:"))
        self.label_10.setText(_translate("MainWindow", "gy"))
        self.label.setText(_translate("MainWindow", "Aceleración en X:"))
        self.label_13.setText(_translate("MainWindow", "Tabla con 5 Peaks"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Graph5Peaks = QtWidgets.QGraph5Peaks()
    ui = Ui_5Peaks()
    ui.setupUi(Graph5Peaks)
    Graph5Peaks.show()
    sys.exit(app.exec_())